// Generated by IB v0.2.10 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation Camera

@end


@implementation ParserError

@end


@implementation NSNotificationCenter

@end


@implementation NSURLRequest

@end


@implementation UIView

@end


@implementation UIViewController

@end


@implementation Response

@end


@implementation Query

@end


@implementation InvalidURLError

@end


@implementation InvalidFileError

@end


@implementation PeriodicTimer

@end


@implementation Queue

@end


@implementation Timer

@end


@implementation RSSParser

@end


@implementation RSSItem

@end


@implementation InvalidPlayerType

@end


@implementation NilPlayerCallback

@end


@implementation Player

@end


@implementation AnimationChain

@end


@implementation CLLocationCoordinate2D

@end


@implementation String

@end


@implementation SugarNotFoundException

@end


@implementation Fixnum

@end


@implementation NSArray

@end


@implementation NSCoder

@end


@implementation NSData

@end


@implementation NSDate

@end


@implementation NSIndexPath

@end


@implementation IndexPath

@end


@implementation NSIndexSet

@end


@implementation NSString

@end


@implementation NSString

@end


@implementation NSURL

@end


@implementation NSUserDefaults

@end


@implementation Object

@end


@implementation NilClass

@end


@implementation NSArray

@end


@implementation NSDictionary

@end


@implementation Numeric

@end


@implementation Symbol

@end


@implementation Symbol

@end


@implementation Numeric

@end


@implementation NSError

@end


@implementation NSLayoutConstraint

@end


@implementation NSSet

@end


@implementation NSURL

@end


@implementation UIColor

@end


@implementation UIEvent

@end


@implementation UILabel

@end


@implementation UITextField

@end


@implementation UITouch

@end


@implementation UIView

@end


@implementation UIViewController

@end


@implementation UIActionSheet

@end


@implementation UIActivityIndicatorView

@end


@implementation UIAlertView

@end


@implementation UIBarButtonItem

@end


@implementation UIButton

@end


@implementation UIColor

@end


@implementation UIControl

@end


@implementation UIImage

@end


@implementation UILabel

@end


@implementation UISegmentedControl

@end


@implementation UITextView

@end


@implementation UIView

@end


@implementation UIViewController

@end


@implementation UINavigationController

@end


@implementation UITabBarController

@end


@implementation AppDelegate

@end


@implementation FavWordController

@end


@implementation RandomWordController

@end


@implementation WotdController

@end



